#!/usr/bin/env ansible-playbook
- name: 
    Linux postinstallation
  hosts: 
    localhost
  vars:
    hostname: ws-soldatkichev
  tasks:
   - name: set a hostname
     ansible.builtin.hostname:
       name: "{{ hostname }}"
     become: True
   - name: set timezone
     community.general.timezone:
       name: Europe/Moscow
       hwclock: UTC
   - name: disable IPv6 (1)
     ansible.posix.sysctl:
       name: net.ipv6.conf.all.disable_ipv6
       value: '1'
       sysctl_set: yes
       reload: yes
       sysctl_file: /etc/sysctl.d/99-sysctl.conf
   - name: disable IPv6 (2)
     ansible.posix.sysctl:
       name: net.ipv6.conf.default.disable_ipv6
       value: '1'
       sysctl_set: yes
       reload: yes
       sysctl_file: /etc/sysctl.d/99-sysctl.conf
   - name: OS specific tasks
     ansible.builtin.debug:
       msg: "{{ item }}"
     with_first_found:
         - "{{ansible_distribution}}.yml"
